### ISSUE TITLE
[BUG] - Getting ambiguous name error with v1.9.0

### ISSUE THREAD

**Issue by ithinkicancode** [veeso/tui-realm#55]
## Description

Getting the following error (and many other similar errors) when upgrading to v1.9.0:

```
error[E0659]: `style` is ambiguous
 --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tuirealm-1.9.0/src/utils/parser.rs:6:17
  |
6 | use crate::tui::style::Color;
  |                 ^^^^^ ambiguous name
  |
  = note: ambiguous because of multiple glob imports of a name in the same module
note: `style` could refer to the module imported here
 --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tuirealm-1.9.0/src/tui.rs:6:9
  |
6 | pub use ratatui::*;
  |         ^^^^^^^^^^
  = help: consider adding an explicit import of `style` to disambiguate
note: `style` could also refer to the module imported here
 --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tuirealm-1.9.0/src/tui.rs:8:9
  |
8 | pub use tui::*;
  |         ^^^^^^
  = help: consider adding an explicit import of `style` to disambiguate
```

## Steps to reproduce

Just upgrade tui-realm to v1.9.0

## Expected behaviour

Should not get these ambiguous name errors.

## Environment

- OS: MacOS ventura
- Architecture [Arm]
- Rust version: 1.71
- tui-realm version: 1.9.0

**Comment by veeso** [comment]
Check your Cargo.toml

the features have changed:

You now have to specify both the tui library `tui` or `ratatui` and the backend `termion` or `crossterm`.

```toml
tuirealm = { version = "^1.9.0", default-features = false, features = [ "ratatui", "derive", "crossterm" ]}
```

**Comment by ithinkicancode** [comment]
I thought the docs say "ratatui" is the default and I think your toml file says that too. :)

Anyhow, I just tried using `tuirealm = { version = "^1.9.0", default-features = false, features = [ "ratatui", "derive", "crossterm" ]}`. I still got the same errors. Is there anything else that I'd need to change?

Could you try creating a hello world project with `tuirealm` 1.9? :)

**Comment by veeso** [comment]
mhm, weird, maybe it's a cache issue. Try to clean your .cargo/registry

**Comment by ithinkicancode** [comment]
I did `cargo cache -a` and recompiled, still got the same errors. :-(

**Comment by Redhawk18** [comment]
[I get the same problem with this sister crate ](https://github.com/Redhawk18/tui-realm-textarea)

**Comment by veeso** [comment]
I confirm this is an issue related to registry cache. It happens because cargo saves sources in your cargo path. Unfortunately the only way is to delete the source folder contained in the error
