### PR TITLE
feat: no_std with alloc support

### PR DESCRIPTION
**Pull request by sbechet**
Here you can find first steps.

One breaking change: Application now has a fourth generic parameter
C: Clock. For std users, specify StdClock explicitly: Application<Id, Msg, Event, StdClock>

Next steps:
- will refactor EventListener for no_std (polling-based)
- will refactor terminal backends for no_std
- Then full no_std compilation will work

### CODE REVIEW

**Review by veeso — COMMENTED** [review]
Great! Looks good so far.

There are some new lines missing in some files for some reason.

Please improve the PR title and body to match what is being done here (so added `Clock` and replaced `std` with `core`).

**Review by hasezoey — CHANGES_REQUESTED** [review]
Overall, this looks to be a good change, but there is some formatting and missing information. I also have some extra questions:
- you still list `+alloc`, which i interpret as `no alloc` support, is this correct? If yes, how do you want to achieve that, as tui-realm heavily relies on Vec,Box and some other things?
- i see that many `core::` imports are now done, but are they not already in `core::prelude`, so they could still be omitted like in `std` environments?

Additionally, as you have noted some extra steps that need to be done (likely more PRs), could you:
- add a github ci workflow (job) to test no-std support?
- add documentation on how `no_std` support is meant to be used in `tui-realm` and what limitations it will have?

Finally, due to this being a multi-step PR and will likely need some more testing, what do you think about changing the base branch to something like `feature/no_std` (which is based on `feature/4.0`) for now until it is done?

File: src/core/compat.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+//! Compatibility layer for collections that works in both std and no_std environments
+//!
+//! This module provides a unified interface for collection types that can work
+//! in both std and no_std+alloc environments.
```
[the remark this answers is not in the document]
Comment (sbechet) [reply src/core/compat.rs]: I will correct it.

File: src/core/props/texts.rs [hunk 2]
```diff
@@ -1,6 +1,7 @@
 //! `Texts` is the module which defines the texts properties for components.
 //! It also provides some helpers and builders to facilitate the use of builders.
-
+use alloc::vec;
```
[the remark this answers is not in the document]
Comment (sbechet) [reply src/core/props/texts.rs]: src/core/props/texts.rs:85:24
   |
85 |             table.push(vec![]);

File: src/listener/builder.rs [hunk 3]
```diff
@@ -169,7 +172,7 @@ where
         let sync_tick_interval = self.tick_interval;
         #[cfg(feature = "async-ports")]
         let sync_tick_interval = self.tick_interval.take_if(|_| !self.async_tick);
-        let mut res = EventListener::new();
+        let mut res: EventListener<UserEvent> = EventListener::<UserEvent>::new();
```
[the remark this answers is not in the document]
Comment (sbechet) [reply src/listener/builder.rs]: I'll try to simplify but:

error[E0283]: type annotations needed for `EventListener<_>`
   --> src/listener/builder.rs:175:13
    |
175 |         let mut res = EventListener::new();
    |             ^^^^^^^   ------------- type must be known at this point
    |
    = note: cannot satisfy `_: core::cmp::Eq`
note: required by a bound in `EventListener`
   --> src/listener/mod.rs:117:16
    |
115 | pub(crate) struct EventListener<UserEvent>
    |                   ------------- required by a bound in this struct
116 | where
117 |     UserEvent: Eq + PartialEq + Clone + Send + 'static,
    |                ^^ required by this bound in `EventListener`
help: consider giving `res` an explicit type, where the type for type parameter `UserEvent` is specified
    |
175 |         let mut res: EventListener<UserEvent> = EventListener::new();
    |                    ++++++++++++++++++++++++++

error[E0282]: type annotations needed

File: src/core/application.rs [hunk 4]
```diff
@@ -17,40 +17,51 @@ use crate::{
     AttrValue, Attribute, Component, Event, Injector, State, Sub, SubEventClause, ViewError,
 };
 
+#[cfg(feature = "std")]
+pub type StdApplication<ComponentId, Msg, UserEvent> =
+    Application<ComponentId, Msg, UserEvent, StdClock>;
```
[the remark this answers is not in the document]
Comment (hasezoey) [reply src/core/application.rs]: > Make StdClock exist unconditionally (even in no_std environments)

Right, didnt quite consider that.

> If the problem is having "Application" in the std apps, I could do it differently by renaming the current "Application" structure pub struct CoreApplication<ComponentId, Msg, UserEvent, ClockImpl> which would remain generic and renaming the type "StdApplication" to "Application" with ClockImpl = StdClock this time?

This was the main issue, so yes it would be great to still have the normal `Application` for the `std` case.

**Comment by hasezoey** [comment]
> > Finally, due to this being a multi-step PR and will likely need some more testing, what do you think about changing the base branch to something like `feature/no_std` (which is based on `feature/4.0`) for now until it is done?
> 
> Okay, I'll do that for the next PRs. I hesitated, I didn't think I would need to break the Application structure for the core work, that's why I didn't make branches.

I didnt even notice that you were working on *your* `feature/4.0` branch, i meant if we should change the *PR*s **base branch** (the branch this PR is going to be merged *into*) to something like `feature/no_std`, until all the work is done.

File: Cargo.toml [hunk 5]
```diff
@@ -22,6 +22,7 @@ async-trait = { version = "0.1", optional = true }
 bitflags = "2"
 dyn-clone = "1"
 futures-util = { version = "0.3", default-features = false, optional = true }
+hashbrown = { version = "0.16", optional = true }
 lazy-regex = "3"
 ratatui = { version = "0.30", default-features = false, features = ["std", "layout-cache"] }
```
[the remark this answers is not in the document]
Comment (sbechet) [reply Cargo.toml]: done.

**Review by veeso — CHANGES_REQUESTED** [review]
Looking good

**Comment by hasezoey** [comment]
As this has been closed without reason:
Due to the monorepo merge, a lot of merge conflicts might have been present and a lot needs to be adjusted, as this now no longer only concerns core but also all stdlib (and maybe others).

Additionally, as this seems to be a change on the smaller side for the outside API, i think this can be introduced later than 4.0

**Comment by veeso** [comment]
@hasezoey I didn't close it, Github closed it automatically because the history conflicts D: I will it later after rebasing the branch.
